rm(list = ls())
getwd()
setwd("./Data/")
library(stringr)

# first read the csv file generated by tcptrace as features
# read the dataset as characters to avoid numeric rounding
trace <- read.csv("lbl.csv", comment.char = "#", colClasses = 'character', header = F,skip = 10)
trace <- trace[,-ncol(trace)]

# read the colnames and set trace to the colnames
cnames <- readLines("lbl.csv",10)[10]
cnames <- strsplit(cnames, ",", fixed = T)
names(trace) <- sub("#", "num", cnames[[1]], fixed = T)

# regularize timestamp to 1096920221.XXXXX to 1096920221.0XXXXX
first.idx <- which(str_length(trace$first_packet) == 17)
trace$first_packet[first.idx] <- sub("\\.","\\.0",trace$first_packet[first.idx])
last.idx <- which(str_length(trace$last_packet) == 17)
trace$last_packet[last.idx] <- sub("\\.","\\.0",trace$first_packet[last.idx])

# add two column indicating a human readable time stamp
trace$first_packet_time <- as.POSIXct(as.numeric(trace$first_packet), origin = "1970-01-01")
trace$last_packet_time <- as.POSIXct(as.numeric(trace$last_packet), origin = "1970-01-01")

# trim all the beginning and ending spaces of trace
trace <- as.data.frame(apply(trace, 2, str_trim))

# have a brief look at the trace dataset and write it to csv
View(trace)
write.csv(trace, "trace.csv", quote = F)

# now read the packet timestamp file generated by tcpdump
# read the time stamp of every packet 
# date <- str_extract(lines,"\\d{4}-\\d{2}-\\d{2}")
# time <- str_extract(lines, "\\d{2}:\\d{2}:\\d{2}.\\d+")

# extract timestamp features using regular expression
lines <- readLines("packet_timestamp.txt")
stamp <- str_extract(lines,"\\d+\\.\\d{6}")
srcip <- sub("IP ", "", str_extract(lines, "IP\\s\\d+\\.\\d+\\.\\d+.\\d+"))
srcport <- sub(" >", "", str_extract(lines, "\\d+\\s>"))
dstip <- sub("> ", "", str_extract(lines, "> \\d+.\\d+.\\d+.\\d+"))
dstport <- gsub("\\.|:", "", str_extract(lines, "\\.\\d+:"))
flag <- str_extract(lines,"\\[(.{1}|.{2})\\]")
seq <- sub("seq ", "",str_extract(lines, "seq\\s\\d+:\\d+"))
ack <- sub("ack ", "", str_extract(lines, "ack\\s\\d+"))
win <- sub("win ", "", str_extract(lines, "win\\s\\d+"))
length <- sub("length ", "", str_extract(lines, "length\\s\\d+"))

timestamp <- data.frame(stamp = stamp, srcip = srcip, srcport = srcport,
                  dstip = dstip, dstport = dstport, flag = flag, ack = ack, win = win, length = length)
write.csv(timestamp, "timestamp.csv", quote = F)

# remove all temperative files except trace and timestamp
rm(list=setdiff(ls(), c("trace", "timestamp")))

View(trace)
View(timestamp)


trace$host_a

flow.begin <- as.character(trace[1,]$first_packet)
flow.end <- as.character(trace[1,]$last_packet)
bidx <- which(timestamp$stamp == flow.begin)
eidx <- which(timestamp$stamp == flow.end)
host.a <- as.character(trace[1,]$host_a)
port.a <- as.character(trace[1,]$port_a)
host.b <- as.character(trace[1,]$host_b)
port.b <- as.character(trace[1,]$port_b)

port.a

coma2b <- subset(timestamp[bidx:eidx, ], (srcip == host.a)&(dstip == host.b)&(srcport == port.a)&(dstport == port.b))
comb2a <- subset(timestamp[bidx:eidx, ], (srcip == host.b)&(dstip == host.a)&(srcport == port.b)&(dstport == port.a))


View(coma2b)
View(comb2a)


timestamp[bidx,]
timestamp[eidx,]


df <- as.data.frame(matrix(rnorm(360), ncol = 6))
df$idx <- rep(c(1:6), each = (nrow(df)/6))
